-- versi Manual
CREATE TABLE skema(
    Kd_skema varchar(255) primary key,
    Nm_skema varchar(255),
    jenis varchar(255),
    Jml_unit int
);

CREATE TABLE peserta(
    Id_peserta serial primary key,
    Kd_skema varchar(255),
    Nm_peserta varchar(255),
    Jekel varchar(255),
    Alamat varchar(255),
    No_hp varchar(255),
    constraint fk_skema foreign key (Kd_skema) references skema(Kd_skema)
);

--hasil postgress
-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.peserta
(
    id_peserta integer NOT NULL DEFAULT nextval('peserta_id_peserta_seq'::regclass),
    kd_skema character varying(255) COLLATE pg_catalog."default",
    nm_peserta character varying(255) COLLATE pg_catalog."default",
    jekel character varying(255) COLLATE pg_catalog."default",
    alamat character varying(255) COLLATE pg_catalog."default",
    no_hp character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT peserta_pkey PRIMARY KEY (id_peserta)
);

CREATE TABLE IF NOT EXISTS public.skema
(
    kd_skema character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nm_skema character varying(255) COLLATE pg_catalog."default",
    jenis character varying(255) COLLATE pg_catalog."default",
    jml_unit integer,
    CONSTRAINT skema_pkey PRIMARY KEY (kd_skema)
);

ALTER TABLE IF EXISTS public.peserta
    ADD CONSTRAINT fk_skema FOREIGN KEY (kd_skema)
    REFERENCES public.skema (kd_skema) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS fki_fk_skema
    ON public.peserta(kd_skema);

END;